create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create schema if not exists private;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function private.catalog_compose_key(
  country_code text,
  source_name text,
  entity_kind text,
  source_identifier text
)
returns text
language sql
immutable
as $$
  select lower(country_code) || ':' || lower(source_name) || ':' || lower(entity_kind) || ':' || source_identifier;
$$;

create or replace function private.catalog_family_key(
  country_code text,
  source_name text,
  family_identifier text
)
returns text
language sql
immutable
as $$
  select case
    when family_identifier is null or btrim(family_identifier) = '' then null
    else lower(country_code) || ':' || lower(source_name) || ':family:' || family_identifier
  end;
$$;

create table if not exists public.catalog_it_raw_products (
  source text not null default 'aifa',
  source_product_id text primary key,
  family_id text,
  display_name text not null,
  brand_name text,
  generic_name text,
  dosage_form text,
  routes jsonb not null default '[]'::jsonb,
  strength_text text,
  manufacturer_name text,
  requires_prescription boolean,
  availability text not null default 'unknown' check (availability in ('active', 'inactive', 'shortage', 'suspended', 'revoked', 'unknown')),
  atc_codes jsonb not null default '[]'::jsonb,
  regulatory jsonb not null default '{}'::jsonb,
  source_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.catalog_it_raw_packages (
  source_package_id text primary key,
  source_product_id text not null references public.catalog_it_raw_products(source_product_id) on delete cascade,
  package_code text,
  display_name text not null,
  unit_count integer,
  package_type text,
  strength_value numeric,
  strength_unit text,
  volume_value numeric,
  volume_unit text,
  strength_text text,
  marketed boolean,
  marketing_start_date date,
  marketing_end_date date,
  is_sample boolean,
  requires_prescription boolean,
  reimbursement_class text,
  reimbursement_text text,
  shortage_reason text,
  shortage_start_date date,
  shortage_end_date date,
  availability text not null default 'unknown' check (availability in ('active', 'inactive', 'shortage', 'suspended', 'revoked', 'unknown')),
  source_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.catalog_it_raw_ingredients (
  id bigint generated by default as identity primary key,
  source_product_id text not null references public.catalog_it_raw_products(source_product_id) on delete cascade,
  name text not null,
  strength_value numeric,
  strength_unit text,
  strength_text text,
  sort_order integer not null default 0
);

create table if not exists public.catalog_us_raw_products (
  source text not null default 'fda_ndc',
  source_product_id text primary key,
  family_id text,
  display_name text not null,
  brand_name text,
  generic_name text,
  dosage_form text,
  routes jsonb not null default '[]'::jsonb,
  strength_text text,
  manufacturer_name text,
  requires_prescription boolean,
  availability text not null default 'unknown' check (availability in ('active', 'inactive', 'shortage', 'suspended', 'revoked', 'unknown')),
  atc_codes jsonb not null default '[]'::jsonb,
  regulatory jsonb not null default '{}'::jsonb,
  source_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.catalog_us_raw_packages (
  source_package_id text primary key,
  source_product_id text not null references public.catalog_us_raw_products(source_product_id) on delete cascade,
  package_code text,
  display_name text not null,
  unit_count integer,
  package_type text,
  strength_value numeric,
  strength_unit text,
  volume_value numeric,
  volume_unit text,
  strength_text text,
  marketed boolean,
  marketing_start_date date,
  marketing_end_date date,
  is_sample boolean,
  requires_prescription boolean,
  reimbursement_class text,
  reimbursement_text text,
  shortage_reason text,
  shortage_start_date date,
  shortage_end_date date,
  availability text not null default 'unknown' check (availability in ('active', 'inactive', 'shortage', 'suspended', 'revoked', 'unknown')),
  source_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.catalog_us_raw_ingredients (
  id bigint generated by default as identity primary key,
  source_product_id text not null references public.catalog_us_raw_products(source_product_id) on delete cascade,
  name text not null,
  strength_value numeric,
  strength_unit text,
  strength_text text,
  sort_order integer not null default 0
);

create index if not exists catalog_it_raw_products_display_name_trgm on public.catalog_it_raw_products using gin (display_name gin_trgm_ops);
create index if not exists catalog_it_raw_products_generic_name_trgm on public.catalog_it_raw_products using gin (generic_name gin_trgm_ops);
create index if not exists catalog_it_raw_products_family_id_idx on public.catalog_it_raw_products (family_id);
create index if not exists catalog_it_raw_packages_source_product_id_idx on public.catalog_it_raw_packages (source_product_id);
create index if not exists catalog_it_raw_packages_package_code_idx on public.catalog_it_raw_packages (package_code);
create index if not exists catalog_it_raw_packages_display_name_trgm on public.catalog_it_raw_packages using gin (display_name gin_trgm_ops);
create index if not exists catalog_it_raw_ingredients_source_product_id_idx on public.catalog_it_raw_ingredients (source_product_id);

create index if not exists catalog_us_raw_products_display_name_trgm on public.catalog_us_raw_products using gin (display_name gin_trgm_ops);
create index if not exists catalog_us_raw_products_generic_name_trgm on public.catalog_us_raw_products using gin (generic_name gin_trgm_ops);
create index if not exists catalog_us_raw_products_family_id_idx on public.catalog_us_raw_products (family_id);
create index if not exists catalog_us_raw_packages_source_product_id_idx on public.catalog_us_raw_packages (source_product_id);
create index if not exists catalog_us_raw_packages_package_code_idx on public.catalog_us_raw_packages (package_code);
create index if not exists catalog_us_raw_packages_display_name_trgm on public.catalog_us_raw_packages using gin (display_name gin_trgm_ops);
create index if not exists catalog_us_raw_ingredients_source_product_id_idx on public.catalog_us_raw_ingredients (source_product_id);

drop trigger if exists set_catalog_it_raw_products_updated_at on public.catalog_it_raw_products;
create trigger set_catalog_it_raw_products_updated_at
before update on public.catalog_it_raw_products
for each row execute function private.touch_updated_at();

drop trigger if exists set_catalog_it_raw_packages_updated_at on public.catalog_it_raw_packages;
create trigger set_catalog_it_raw_packages_updated_at
before update on public.catalog_it_raw_packages
for each row execute function private.touch_updated_at();

drop trigger if exists set_catalog_us_raw_products_updated_at on public.catalog_us_raw_products;
create trigger set_catalog_us_raw_products_updated_at
before update on public.catalog_us_raw_products
for each row execute function private.touch_updated_at();

drop trigger if exists set_catalog_us_raw_packages_updated_at on public.catalog_us_raw_packages;
create trigger set_catalog_us_raw_packages_updated_at
before update on public.catalog_us_raw_packages
for each row execute function private.touch_updated_at();

create or replace view public.catalog_it_search_v1 as
select
  'it'::text as country,
  p.source,
  private.catalog_compose_key('it', p.source, 'product', p.source_product_id) as product_id,
  private.catalog_compose_key('it', p.source, 'package', pk.source_package_id) as package_id,
  private.catalog_family_key('it', p.source, p.family_id) as family_id,
  p.display_name,
  p.brand_name,
  p.generic_name,
  coalesce(
    nullif(p.generic_name, ''),
    nullif((
      select string_agg(ci.name, ', ' order by ci.sort_order, ci.id)
      from public.catalog_it_raw_ingredients ci
      where ci.source_product_id = p.source_product_id
    ), ''),
    p.display_name
  ) as principle,
  coalesce(pk.requires_prescription, p.requires_prescription, false) as requires_prescription,
  pk.display_name as package_label,
  coalesce(pk.unit_count, 1) as units,
  coalesce(nullif(pk.package_type, ''), pk.display_name, 'Package') as tipologia,
  coalesce(round(pk.strength_value)::integer, 0) as valore,
  coalesce(pk.strength_unit, '') as unita,
  case
    when pk.volume_value is null or pk.volume_unit is null or btrim(pk.volume_unit) = '' then ''
    else trim(to_char(pk.volume_value, 'FM999999990.########')) || ' ' || pk.volume_unit
  end as volume,
  coalesce(pk.availability, p.availability, 'unknown') as availability,
  pk.package_code as catalog_code,
  jsonb_build_object(
    'country', 'it',
    'source', p.source,
    'product_id', private.catalog_compose_key('it', p.source, 'product', p.source_product_id),
    'package_id', private.catalog_compose_key('it', p.source, 'package', pk.source_package_id),
    'family_id', private.catalog_family_key('it', p.source, p.family_id),
    'display_name', p.display_name,
    'generic_name', p.generic_name,
    'package_label', pk.display_name,
    'catalog_code', pk.package_code,
    'availability', coalesce(pk.availability, p.availability, 'unknown')
  ) as catalog_snapshot
from public.catalog_it_raw_products p
join public.catalog_it_raw_packages pk on pk.source_product_id = p.source_product_id;

create or replace view public.catalog_us_search_v1 as
select
  'us'::text as country,
  p.source,
  private.catalog_compose_key('us', p.source, 'product', p.source_product_id) as product_id,
  private.catalog_compose_key('us', p.source, 'package', pk.source_package_id) as package_id,
  private.catalog_family_key('us', p.source, p.family_id) as family_id,
  p.display_name,
  p.brand_name,
  p.generic_name,
  coalesce(
    nullif(p.generic_name, ''),
    nullif((
      select string_agg(ci.name, ', ' order by ci.sort_order, ci.id)
      from public.catalog_us_raw_ingredients ci
      where ci.source_product_id = p.source_product_id
    ), ''),
    p.display_name
  ) as principle,
  coalesce(pk.requires_prescription, p.requires_prescription, false) as requires_prescription,
  pk.display_name as package_label,
  coalesce(pk.unit_count, 1) as units,
  coalesce(nullif(pk.package_type, ''), pk.display_name, 'Package') as tipologia,
  coalesce(round(pk.strength_value)::integer, 0) as valore,
  coalesce(pk.strength_unit, '') as unita,
  case
    when pk.volume_value is null or pk.volume_unit is null or btrim(pk.volume_unit) = '' then ''
    else trim(to_char(pk.volume_value, 'FM999999990.########')) || ' ' || pk.volume_unit
  end as volume,
  coalesce(pk.availability, p.availability, 'unknown') as availability,
  pk.package_code as catalog_code,
  jsonb_build_object(
    'country', 'us',
    'source', p.source,
    'product_id', private.catalog_compose_key('us', p.source, 'product', p.source_product_id),
    'package_id', private.catalog_compose_key('us', p.source, 'package', pk.source_package_id),
    'family_id', private.catalog_family_key('us', p.source, p.family_id),
    'display_name', p.display_name,
    'generic_name', p.generic_name,
    'package_label', pk.display_name,
    'catalog_code', pk.package_code,
    'availability', coalesce(pk.availability, p.availability, 'unknown')
  ) as catalog_snapshot
from public.catalog_us_raw_products p
join public.catalog_us_raw_packages pk on pk.source_product_id = p.source_product_id;

create or replace view public.catalog_search_v1 as
select * from public.catalog_it_search_v1
union all
select * from public.catalog_us_search_v1;

create or replace view public.catalog_it_package_detail_v1 as
select
  private.catalog_compose_key('it', p.source, 'package', pk.source_package_id) as id,
  pk.source_package_id,
  pk.package_code,
  pk.display_name,
  pk.unit_count,
  pk.package_type,
  pk.volume_value,
  pk.volume_unit,
  pk.strength_text,
  pk.marketed,
  pk.marketing_start_date,
  pk.marketing_end_date,
  pk.is_sample,
  pk.requires_prescription,
  pk.reimbursement_class,
  pk.reimbursement_text,
  pk.shortage_reason,
  pk.shortage_start_date,
  pk.shortage_end_date,
  pk.availability,
  pk.source_meta
from public.catalog_it_raw_products p
join public.catalog_it_raw_packages pk on pk.source_product_id = p.source_product_id;

create or replace view public.catalog_us_package_detail_v1 as
select
  private.catalog_compose_key('us', p.source, 'package', pk.source_package_id) as id,
  pk.source_package_id,
  pk.package_code,
  pk.display_name,
  pk.unit_count,
  pk.package_type,
  pk.volume_value,
  pk.volume_unit,
  pk.strength_text,
  pk.marketed,
  pk.marketing_start_date,
  pk.marketing_end_date,
  pk.is_sample,
  pk.requires_prescription,
  pk.reimbursement_class,
  pk.reimbursement_text,
  pk.shortage_reason,
  pk.shortage_start_date,
  pk.shortage_end_date,
  pk.availability,
  pk.source_meta
from public.catalog_us_raw_products p
join public.catalog_us_raw_packages pk on pk.source_product_id = p.source_product_id;

create or replace view public.catalog_it_product_detail_v1 as
select
  private.catalog_compose_key('it', p.source, 'product', p.source_product_id) as id,
  'it'::text as country,
  p.source,
  p.source_product_id,
  private.catalog_family_key('it', p.source, p.family_id) as family_id,
  p.display_name,
  p.brand_name,
  p.generic_name,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'name', ci.name,
        'strength_value', ci.strength_value,
        'strength_unit', ci.strength_unit,
        'strength_text', ci.strength_text
      )
      order by ci.sort_order, ci.id
    )
    from public.catalog_it_raw_ingredients ci
    where ci.source_product_id = p.source_product_id
  ), '[]'::jsonb) as active_ingredients,
  p.dosage_form,
  p.routes,
  p.strength_text,
  p.manufacturer_name,
  p.requires_prescription,
  p.availability,
  p.atc_codes,
  p.regulatory,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', private.catalog_compose_key('it', p.source, 'package', pk.source_package_id),
        'source_package_id', pk.source_package_id,
        'package_code', pk.package_code,
        'display_name', pk.display_name,
        'unit_count', pk.unit_count,
        'package_type', pk.package_type,
        'volume_value', pk.volume_value,
        'volume_unit', pk.volume_unit,
        'strength_text', pk.strength_text,
        'marketed', pk.marketed,
        'marketing_start_date', pk.marketing_start_date,
        'marketing_end_date', pk.marketing_end_date,
        'is_sample', pk.is_sample,
        'requires_prescription', pk.requires_prescription,
        'reimbursement_class', pk.reimbursement_class,
        'reimbursement_text', pk.reimbursement_text,
        'shortage_reason', pk.shortage_reason,
        'shortage_start_date', pk.shortage_start_date,
        'shortage_end_date', pk.shortage_end_date,
        'availability', pk.availability,
        'source_meta', pk.source_meta
      )
      order by pk.display_name
    )
    from public.catalog_it_raw_packages pk
    where pk.source_product_id = p.source_product_id
  ), '[]'::jsonb) as packages,
  p.source_meta
from public.catalog_it_raw_products p;

create or replace view public.catalog_us_product_detail_v1 as
select
  private.catalog_compose_key('us', p.source, 'product', p.source_product_id) as id,
  'us'::text as country,
  p.source,
  p.source_product_id,
  private.catalog_family_key('us', p.source, p.family_id) as family_id,
  p.display_name,
  p.brand_name,
  p.generic_name,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'name', ci.name,
        'strength_value', ci.strength_value,
        'strength_unit', ci.strength_unit,
        'strength_text', ci.strength_text
      )
      order by ci.sort_order, ci.id
    )
    from public.catalog_us_raw_ingredients ci
    where ci.source_product_id = p.source_product_id
  ), '[]'::jsonb) as active_ingredients,
  p.dosage_form,
  p.routes,
  p.strength_text,
  p.manufacturer_name,
  p.requires_prescription,
  p.availability,
  p.atc_codes,
  p.regulatory,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', private.catalog_compose_key('us', p.source, 'package', pk.source_package_id),
        'source_package_id', pk.source_package_id,
        'package_code', pk.package_code,
        'display_name', pk.display_name,
        'unit_count', pk.unit_count,
        'package_type', pk.package_type,
        'volume_value', pk.volume_value,
        'volume_unit', pk.volume_unit,
        'strength_text', pk.strength_text,
        'marketed', pk.marketed,
        'marketing_start_date', pk.marketing_start_date,
        'marketing_end_date', pk.marketing_end_date,
        'is_sample', pk.is_sample,
        'requires_prescription', pk.requires_prescription,
        'reimbursement_class', pk.reimbursement_class,
        'reimbursement_text', pk.reimbursement_text,
        'shortage_reason', pk.shortage_reason,
        'shortage_start_date', pk.shortage_start_date,
        'shortage_end_date', pk.shortage_end_date,
        'availability', pk.availability,
        'source_meta', pk.source_meta
      )
      order by pk.display_name
    )
    from public.catalog_us_raw_packages pk
    where pk.source_product_id = p.source_product_id
  ), '[]'::jsonb) as packages,
  p.source_meta
from public.catalog_us_raw_products p;

create or replace function public.fetch_catalog_product_v1(country text, product_id text)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  result jsonb;
begin
  if lower(country) not in ('it', 'us') then
    raise exception 'invalid catalog country'
      using errcode = '22023';
  end if;

  if lower(country) = 'it' then
    select to_jsonb(v) into result
    from public.catalog_it_product_detail_v1 v
    where v.id = product_id;
  else
    select to_jsonb(v) into result
    from public.catalog_us_product_detail_v1 v
    where v.id = product_id;
  end if;

  if result is null then
    raise exception 'catalog product not found'
      using errcode = 'P0002';
  end if;

  return result;
end;
$$;

create or replace function public.fetch_catalog_package_v1(country text, package_id text)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  result jsonb;
begin
  if lower(country) not in ('it', 'us') then
    raise exception 'invalid catalog country'
      using errcode = '22023';
  end if;

  if lower(country) = 'it' then
    select to_jsonb(v) into result
    from public.catalog_it_package_detail_v1 v
    where v.id = package_id;
  else
    select to_jsonb(v) into result
    from public.catalog_us_package_detail_v1 v
    where v.id = package_id;
  end if;

  if result is null then
    raise exception 'catalog package not found'
      using errcode = 'P0002';
  end if;

  return result;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  photo_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  catalog_country text not null default 'it' check (catalog_country in ('it', 'us')),
  business_country text not null default 'it' check (business_country in ('it', 'us')),
  day_threshold_stocks_alarm integer not null default 7,
  therapy_notification_level text not null default 'normal' check (therapy_notification_level in ('normal', 'alarm')),
  therapy_snooze_minutes integer not null default 10,
  manual_intake_registration boolean not null default false,
  prescription_message_template text,
  grace_minutes integer not null default 30,
  notify_caregivers boolean not null default false,
  notify_shared boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.people (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  surname text,
  condition text,
  codice_fiscale text,
  is_account boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists people_single_account_per_owner_idx
  on public.people(owner_user_id)
  where is_account = true;

create table if not exists public.doctors (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  surname text,
  email text,
  phone text,
  address text,
  specialization text,
  schedule_json jsonb not null default '{}'::jsonb,
  secretary_name text,
  secretary_email text,
  secretary_phone text,
  secretary_schedule_json jsonb not null default '{}'::jsonb,
  prescription_message_template text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.cabinets (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  is_shared boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.cabinet_memberships (
  id uuid primary key default gen_random_uuid(),
  cabinet_id uuid not null references public.cabinets(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'editor', 'viewer')),
  status text not null check (status in ('active', 'invited', 'revoked')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (cabinet_id, user_id)
);

create table if not exists public.tracked_medicines (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  cabinet_id uuid references public.cabinets(id) on delete set null,
  catalog_country text not null check (catalog_country in ('it', 'us')),
  catalog_source text not null,
  catalog_product_key text not null,
  catalog_family_key text,
  name text not null,
  principle text,
  requires_prescription boolean not null default false,
  labels jsonb not null default '[]'::jsonb,
  custom_stock_threshold integer not null default 0,
  manual_intake_registration boolean not null default false,
  catalog_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tracked_packages (
  id uuid primary key default gen_random_uuid(),
  tracked_medicine_id uuid not null references public.tracked_medicines(id) on delete cascade,
  catalog_country text not null check (catalog_country in ('it', 'us')),
  catalog_source text not null,
  catalog_package_key text not null,
  catalog_code text,
  tipologia text,
  units_per_package integer not null default 1,
  unit_value numeric,
  unit_name text,
  volume text,
  package_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.medicine_entries (
  id uuid primary key default gen_random_uuid(),
  tracked_medicine_id uuid not null references public.tracked_medicines(id) on delete cascade,
  tracked_package_id uuid not null references public.tracked_packages(id) on delete cascade,
  cabinet_id uuid references public.cabinets(id) on delete set null,
  deadline_month integer,
  deadline_year integer,
  purchase_operation_id uuid,
  reversed_by_operation_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.therapies (
  id uuid primary key default gen_random_uuid(),
  tracked_medicine_id uuid not null references public.tracked_medicines(id) on delete cascade,
  tracked_package_id uuid not null references public.tracked_packages(id) on delete cascade,
  medicine_entry_id uuid references public.medicine_entries(id) on delete set null,
  person_id uuid not null references public.people(id) on delete restrict,
  doctor_id uuid references public.doctors(id) on delete set null,
  start_date timestamptz not null,
  rrule text,
  importance text not null default 'standard' check (importance in ('vital', 'essential', 'standard')),
  notification_level text not null default 'normal' check (notification_level in ('normal', 'alarm')),
  notifications_silenced boolean not null default false,
  snooze_minutes integer not null default 10,
  clinical_rules jsonb not null default '{}'::jsonb,
  condition text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.therapy_doses (
  id uuid primary key default gen_random_uuid(),
  therapy_id uuid not null references public.therapies(id) on delete cascade,
  time time not null,
  amount numeric not null,
  sort_order integer not null default 0
);

create table if not exists public.stocks (
  id uuid primary key default gen_random_uuid(),
  tracked_medicine_id uuid not null references public.tracked_medicines(id) on delete cascade,
  tracked_package_id uuid not null references public.tracked_packages(id) on delete cascade,
  context_key text not null default 'default',
  stock_units integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  unique (tracked_package_id, context_key)
);

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  cabinet_id uuid references public.cabinets(id) on delete set null,
  tracked_medicine_id uuid not null references public.tracked_medicines(id) on delete cascade,
  tracked_package_id uuid references public.tracked_packages(id) on delete set null,
  therapy_id uuid references public.therapies(id) on delete set null,
  operation_id uuid not null unique,
  reversal_of_operation_id uuid,
  type text not null check (type in ('intake', 'intake_undo', 'purchase', 'purchase_undo', 'stock_increment', 'stock_adjustment', 'new_prescription_request', 'prescription_request_undo', 'new_prescription', 'prescription_received_undo')),
  timestamp timestamptz not null default timezone('utc', now()),
  scheduled_due_at timestamptz,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_device_id text,
  source text
);

create table if not exists public.dose_events (
  id uuid primary key default gen_random_uuid(),
  therapy_id uuid not null references public.therapies(id) on delete cascade,
  tracked_medicine_id uuid not null references public.tracked_medicines(id) on delete cascade,
  due_at timestamptz not null,
  status text not null check (status in ('planned', 'taken', 'missed', 'skipped')),
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_device_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (therapy_id, due_at)
);

create table if not exists public.monitoring_measurements (
  id uuid primary key default gen_random_uuid(),
  tracked_medicine_id uuid references public.tracked_medicines(id) on delete set null,
  therapy_id uuid references public.therapies(id) on delete set null,
  todo_source_id text unique,
  kind text not null,
  dose_relation text,
  value_primary numeric,
  value_secondary numeric,
  unit text,
  measured_at timestamptz not null default timezone('utc', now()),
  scheduled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notification_locks (
  id uuid primary key default gen_random_uuid(),
  cabinet_id uuid not null references public.cabinets(id) on delete cascade,
  lock_key text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists people_owner_user_id_idx on public.people(owner_user_id);
create index if not exists doctors_owner_user_id_idx on public.doctors(owner_user_id);
create index if not exists cabinets_owner_user_id_idx on public.cabinets(owner_user_id);
create index if not exists cabinet_memberships_user_id_idx on public.cabinet_memberships(user_id);
create index if not exists tracked_medicines_owner_user_id_idx on public.tracked_medicines(owner_user_id);
create index if not exists tracked_medicines_cabinet_id_idx on public.tracked_medicines(cabinet_id);
create index if not exists tracked_medicines_catalog_product_key_idx on public.tracked_medicines(catalog_product_key);
create index if not exists tracked_packages_tracked_medicine_id_idx on public.tracked_packages(tracked_medicine_id);
create index if not exists tracked_packages_catalog_package_key_idx on public.tracked_packages(catalog_package_key);
create index if not exists medicine_entries_tracked_medicine_id_idx on public.medicine_entries(tracked_medicine_id);
create index if not exists medicine_entries_tracked_package_id_idx on public.medicine_entries(tracked_package_id);
create index if not exists medicine_entries_cabinet_id_idx on public.medicine_entries(cabinet_id);
create index if not exists therapies_tracked_medicine_id_idx on public.therapies(tracked_medicine_id);
create index if not exists therapies_person_id_idx on public.therapies(person_id);
create index if not exists therapy_doses_therapy_id_idx on public.therapy_doses(therapy_id);
create index if not exists stocks_tracked_medicine_id_idx on public.stocks(tracked_medicine_id);
create index if not exists activity_logs_owner_user_id_idx on public.activity_logs(owner_user_id);
create index if not exists activity_logs_cabinet_id_idx on public.activity_logs(cabinet_id);
create index if not exists activity_logs_tracked_medicine_id_idx on public.activity_logs(tracked_medicine_id);
create index if not exists activity_logs_reversal_of_operation_id_idx on public.activity_logs(reversal_of_operation_id);
create index if not exists dose_events_tracked_medicine_id_idx on public.dose_events(tracked_medicine_id);
create index if not exists monitoring_measurements_tracked_medicine_id_idx on public.monitoring_measurements(tracked_medicine_id);
create index if not exists notification_locks_cabinet_id_idx on public.notification_locks(cabinet_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function private.touch_updated_at();

drop trigger if exists set_user_settings_updated_at on public.user_settings;
create trigger set_user_settings_updated_at
before update on public.user_settings
for each row execute function private.touch_updated_at();

drop trigger if exists set_people_updated_at on public.people;
create trigger set_people_updated_at
before update on public.people
for each row execute function private.touch_updated_at();

drop trigger if exists set_doctors_updated_at on public.doctors;
create trigger set_doctors_updated_at
before update on public.doctors
for each row execute function private.touch_updated_at();

drop trigger if exists set_cabinets_updated_at on public.cabinets;
create trigger set_cabinets_updated_at
before update on public.cabinets
for each row execute function private.touch_updated_at();

drop trigger if exists set_cabinet_memberships_updated_at on public.cabinet_memberships;
create trigger set_cabinet_memberships_updated_at
before update on public.cabinet_memberships
for each row execute function private.touch_updated_at();

drop trigger if exists set_tracked_medicines_updated_at on public.tracked_medicines;
create trigger set_tracked_medicines_updated_at
before update on public.tracked_medicines
for each row execute function private.touch_updated_at();

drop trigger if exists set_tracked_packages_updated_at on public.tracked_packages;
create trigger set_tracked_packages_updated_at
before update on public.tracked_packages
for each row execute function private.touch_updated_at();

drop trigger if exists set_medicine_entries_updated_at on public.medicine_entries;
create trigger set_medicine_entries_updated_at
before update on public.medicine_entries
for each row execute function private.touch_updated_at();

drop trigger if exists set_therapies_updated_at on public.therapies;
create trigger set_therapies_updated_at
before update on public.therapies
for each row execute function private.touch_updated_at();

drop trigger if exists set_dose_events_updated_at on public.dose_events;
create trigger set_dose_events_updated_at
before update on public.dose_events
for each row execute function private.touch_updated_at();

create or replace function private.user_can_access_cabinet(target_cabinet_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, private
as $$
  select exists (
    select 1
    from public.cabinets c
    left join public.cabinet_memberships cm
      on cm.cabinet_id = c.id
     and cm.user_id = auth.uid()
     and cm.status = 'active'
    where c.id = target_cabinet_id
      and (
        c.owner_user_id = auth.uid()
        or cm.id is not null
      )
  );
$$;

create or replace function private.user_can_access_tracked_medicine(target_tracked_medicine_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, private
as $$
  select exists (
    select 1
    from public.tracked_medicines tm
    where tm.id = target_tracked_medicine_id
      and (
        tm.owner_user_id = auth.uid()
        or (tm.cabinet_id is not null and private.user_can_access_cabinet(tm.cabinet_id))
      )
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  given_name text;
  family_name text;
  full_name text;
begin
  given_name := nullif(new.raw_user_meta_data ->> 'given_name', '');
  family_name := nullif(new.raw_user_meta_data ->> 'family_name', '');
  full_name := nullif(new.raw_user_meta_data ->> 'full_name', '');

  insert into public.profiles (id, display_name)
  values (new.id, coalesce(full_name, new.email))
  on conflict (id) do nothing;

  insert into public.user_settings (user_id, catalog_country, business_country)
  values (new.id, 'it', 'it')
  on conflict (user_id) do nothing;

  insert into public.people (owner_user_id, name, surname, is_account)
  values (
    new.id,
    coalesce(given_name, split_part(coalesce(full_name, ''), ' ', 1)),
    coalesce(family_name, nullif(trim(substr(coalesce(full_name, ''), length(split_part(coalesce(full_name, ''), ' ', 1)) + 1)), '')),
    true
  )
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.people enable row level security;
alter table public.doctors enable row level security;
alter table public.cabinets enable row level security;
alter table public.cabinet_memberships enable row level security;
alter table public.tracked_medicines enable row level security;
alter table public.tracked_packages enable row level security;
alter table public.medicine_entries enable row level security;
alter table public.therapies enable row level security;
alter table public.therapy_doses enable row level security;
alter table public.stocks enable row level security;
alter table public.activity_logs enable row level security;
alter table public.dose_events enable row level security;
alter table public.monitoring_measurements enable row level security;
alter table public.notification_locks enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
for insert to authenticated
with check ((select auth.uid()) = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists user_settings_all_own on public.user_settings;
create policy user_settings_all_own on public.user_settings
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists people_all_owner on public.people;
create policy people_all_owner on public.people
for all to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);

drop policy if exists doctors_all_owner on public.doctors;
create policy doctors_all_owner on public.doctors
for all to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);

drop policy if exists cabinets_select_accessible on public.cabinets;
create policy cabinets_select_accessible on public.cabinets
for select to authenticated
using (
  (select auth.uid()) = owner_user_id
  or private.user_can_access_cabinet(id)
);

drop policy if exists cabinets_insert_owner on public.cabinets;
create policy cabinets_insert_owner on public.cabinets
for insert to authenticated
with check ((select auth.uid()) = owner_user_id);

drop policy if exists cabinets_update_owner on public.cabinets;
create policy cabinets_update_owner on public.cabinets
for update to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);

drop policy if exists cabinets_delete_owner on public.cabinets;
create policy cabinets_delete_owner on public.cabinets
for delete to authenticated
using ((select auth.uid()) = owner_user_id);

drop policy if exists cabinet_memberships_select_accessible on public.cabinet_memberships;
create policy cabinet_memberships_select_accessible on public.cabinet_memberships
for select to authenticated
using (
  user_id = auth.uid()
  or private.user_can_access_cabinet(cabinet_id)
);

drop policy if exists cabinet_memberships_manage_owner on public.cabinet_memberships;
create policy cabinet_memberships_manage_owner on public.cabinet_memberships
for all to authenticated
using (
  exists (
    select 1
    from public.cabinets c
    where c.id = cabinet_id
      and c.owner_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.cabinets c
    where c.id = cabinet_id
      and c.owner_user_id = auth.uid()
  )
);

drop policy if exists tracked_medicines_access on public.tracked_medicines;
create policy tracked_medicines_access on public.tracked_medicines
for all to authenticated
using (
  owner_user_id = auth.uid()
  or (cabinet_id is not null and private.user_can_access_cabinet(cabinet_id))
)
with check (
  owner_user_id = auth.uid()
  and (cabinet_id is null or private.user_can_access_cabinet(cabinet_id))
);

drop policy if exists tracked_packages_access on public.tracked_packages;
create policy tracked_packages_access on public.tracked_packages
for all to authenticated
using (private.user_can_access_tracked_medicine(tracked_medicine_id))
with check (private.user_can_access_tracked_medicine(tracked_medicine_id));

drop policy if exists medicine_entries_access on public.medicine_entries;
create policy medicine_entries_access on public.medicine_entries
for all to authenticated
using (
  private.user_can_access_tracked_medicine(tracked_medicine_id)
  or (cabinet_id is not null and private.user_can_access_cabinet(cabinet_id))
)
with check (
  private.user_can_access_tracked_medicine(tracked_medicine_id)
  and (cabinet_id is null or private.user_can_access_cabinet(cabinet_id))
);

drop policy if exists therapies_access on public.therapies;
create policy therapies_access on public.therapies
for all to authenticated
using (private.user_can_access_tracked_medicine(tracked_medicine_id))
with check (private.user_can_access_tracked_medicine(tracked_medicine_id));

drop policy if exists therapy_doses_access on public.therapy_doses;
create policy therapy_doses_access on public.therapy_doses
for all to authenticated
using (
  exists (
    select 1
    from public.therapies t
    where t.id = therapy_id
      and private.user_can_access_tracked_medicine(t.tracked_medicine_id)
  )
)
with check (
  exists (
    select 1
    from public.therapies t
    where t.id = therapy_id
      and private.user_can_access_tracked_medicine(t.tracked_medicine_id)
  )
);

drop policy if exists stocks_access on public.stocks;
create policy stocks_access on public.stocks
for all to authenticated
using (private.user_can_access_tracked_medicine(tracked_medicine_id))
with check (private.user_can_access_tracked_medicine(tracked_medicine_id));

drop policy if exists activity_logs_access on public.activity_logs;
create policy activity_logs_access on public.activity_logs
for all to authenticated
using (
  owner_user_id = auth.uid()
  or private.user_can_access_tracked_medicine(tracked_medicine_id)
  or (cabinet_id is not null and private.user_can_access_cabinet(cabinet_id))
)
with check (
  owner_user_id = auth.uid()
  and (
    private.user_can_access_tracked_medicine(tracked_medicine_id)
    or cabinet_id is null
    or private.user_can_access_cabinet(cabinet_id)
  )
);

drop policy if exists dose_events_access on public.dose_events;
create policy dose_events_access on public.dose_events
for all to authenticated
using (private.user_can_access_tracked_medicine(tracked_medicine_id))
with check (private.user_can_access_tracked_medicine(tracked_medicine_id));

drop policy if exists monitoring_measurements_access on public.monitoring_measurements;
create policy monitoring_measurements_access on public.monitoring_measurements
for all to authenticated
using (
  tracked_medicine_id is null
  or private.user_can_access_tracked_medicine(tracked_medicine_id)
)
with check (
  tracked_medicine_id is null
  or private.user_can_access_tracked_medicine(tracked_medicine_id)
);

drop policy if exists notification_locks_access on public.notification_locks;
create policy notification_locks_access on public.notification_locks
for all to authenticated
using (private.user_can_access_cabinet(cabinet_id))
with check (private.user_can_access_cabinet(cabinet_id));

revoke all on public.catalog_it_raw_products from anon, authenticated;
revoke all on public.catalog_it_raw_packages from anon, authenticated;
revoke all on public.catalog_it_raw_ingredients from anon, authenticated;
revoke all on public.catalog_us_raw_products from anon, authenticated;
revoke all on public.catalog_us_raw_packages from anon, authenticated;
revoke all on public.catalog_us_raw_ingredients from anon, authenticated;

grant select on public.catalog_it_search_v1 to authenticated;
grant select on public.catalog_us_search_v1 to authenticated;
grant select on public.catalog_search_v1 to authenticated;
grant execute on function public.fetch_catalog_product_v1(text, text) to authenticated;
grant execute on function public.fetch_catalog_package_v1(text, text) to authenticated;

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.user_settings to authenticated;
grant select, insert, update, delete on public.people to authenticated;
grant select, insert, update, delete on public.doctors to authenticated;
grant select, insert, update, delete on public.cabinets to authenticated;
grant select, insert, update, delete on public.cabinet_memberships to authenticated;
grant select, insert, update, delete on public.tracked_medicines to authenticated;
grant select, insert, update, delete on public.tracked_packages to authenticated;
grant select, insert, update, delete on public.medicine_entries to authenticated;
grant select, insert, update, delete on public.therapies to authenticated;
grant select, insert, update, delete on public.therapy_doses to authenticated;
grant select, insert, update, delete on public.stocks to authenticated;
grant select, insert, update, delete on public.activity_logs to authenticated;
grant select, insert, update, delete on public.dose_events to authenticated;
grant select, insert, update, delete on public.monitoring_measurements to authenticated;
grant select, insert, update, delete on public.notification_locks to authenticated;

alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.user_settings;
alter publication supabase_realtime add table public.people;
alter publication supabase_realtime add table public.doctors;
alter publication supabase_realtime add table public.cabinets;
alter publication supabase_realtime add table public.cabinet_memberships;
alter publication supabase_realtime add table public.tracked_medicines;
alter publication supabase_realtime add table public.tracked_packages;
alter publication supabase_realtime add table public.medicine_entries;
alter publication supabase_realtime add table public.therapies;
alter publication supabase_realtime add table public.therapy_doses;
alter publication supabase_realtime add table public.stocks;
alter publication supabase_realtime add table public.activity_logs;
alter publication supabase_realtime add table public.dose_events;
alter publication supabase_realtime add table public.monitoring_measurements;
alter publication supabase_realtime add table public.notification_locks;
